name: Decompile APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install Java
      run: sudo apt-get update && sudo apt-get install -y openjdk-17-jdk

    - name: Install Python tools
      run: |
        python3 -m pip install --upgrade pip
        pip install gdown

    - name: Download APK from Google Drive
      run: gdown "https://drive.google.com/uc?id=1-BTwkTg-deXJNDhAdHvlFt9aKKe76DUe" -O game.apk

    - name: Download apktool
      run: wget https://github.com/iBotPeaches/Apktool/releases/download/v2.9.3/apktool_2.9.3.jar -O apktool.jar

    - name: Decompile APK
      run: java -jar apktool.jar d game.apk -o output

    - name: Upload result
      uses: actions/upload-artifact@v4
      with:
        name: decompiled-apk
        path: output
